title Zustandsdiagramm Kunde

[*] ---> erstellen : instanzieren
erstellen -> editieren : ändern


[*] -> deserialisieren : source einlesen
deserialisieren -> erstellen : instanzieren

editieren ---> serialisieren : speichern
serialisieren -> [*] : speichern

editieren --> zerstören : löschen
erstellen --> zerstören : löschen
zerstören --> [*] : speicher freigeben
